name: Create Hosts

on:
  push:
    branches: [ main ]
    paths:
      - 'hosts/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ZABBIX_LOGIN_USER: ${{ secrets.ZABBIX_LOGIN_USER }}
      ZABBIX_LOGIN_PASSWORD: ${{ secrets.ZABBIX_LOGIN_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Hosts
      run: |
        cd hosts
        pip install -r requirements.txt
        python3 add_hosts.py