name: Terraform Create Infrastructure

on:
  push:
    branches: [ main ]
    paths:
      - 'secure_zone/**'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.11

    - name: Initialize Terraform
      run: |
        cd secure_zone
        terraform init
        terraform plan

    - name: Apply Terraform
      run: |
        cd secure_zone
        terraform apply -auto-approve